# Generated by Django 5.2.14 on 2026-05-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='consentimento_lgpd_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimento LGPD em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='raio_busca_km',
            field=models.PositiveIntegerField(default=5, verbose_name='Raio de busca em km'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='receber_notificacoes',
            field=models.BooleanField(default=True, verbose_name='Receber notificações'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
