# Generated by Django 5.2.14 on 2026-05-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('tipos_aceitos', models.CharField(max_length=255, verbose_name='Tipos Aceitos')),
                ('horario_funcionamento', models.CharField(blank=True, default='', max_length=120, verbose_name='Horário de Funcionamento')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('tipo_residuo', models.CharField(max_length=50, verbose_name='Tipo de Resíduo')),
                ('peso_kg', models.FloatField(verbose_name='Peso (kg)')),
                ('pontos_gerados', models.IntegerField(default=0, verbose_name='Pontos Gerados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ponto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes', to='coleta.pontocoleta', verbose_name='Ponto de Coleta')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descartes',
                'ordering': ['-data_hora'],
            },
        ),
    ]
