# Generated by Django 5.2.14 on 2026-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontocoleta',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
