# Generated by Django 5.2.14 on 2026-05-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0002_pontocoleta_descricao_pontocoleta_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontocoleta',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
