# Generated by Django 5.2.14 on 2026-05-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('custo_pontos', models.IntegerField(verbose_name='Custo em Pontos')),
                ('tipo', models.CharField(blank=True, choices=[('DESCONTO', 'Desconto'), ('VOUCHER', 'Voucher'), ('OUTRO', 'Outro')], default='', max_length=50, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resgate', models.DateTimeField(auto_now_add=True, verbose_name='Data do Resgate')),
                ('pontos_utilizados', models.IntegerField(verbose_name='Pontos Utilizados')),
                ('codigo_voucher', models.CharField(max_length=50, verbose_name='Código do Voucher')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('USADO', 'Usado'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('beneficio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resgates', to='recompensas.beneficio', verbose_name='Benefício')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate',
                'verbose_name_plural': 'Resgates',
                'ordering': ['-data_resgate'],
            },
        ),
    ]
